coverage:
  status:
    project:
      default:
        # Disable project-wide coverage checks
        enabled: false
    patch:
      default:
        # Only check coverage on changed lines
        enabled: true
        # Require 80% coverage on changed lines
        target: 80%
        # Allow up to 5% threshold below target
        threshold: 5%

comment:
  # Layout focusing on changed lines coverage
  layout: "header,diff,files,footer"
  # Always post/update comment
  behavior: default
  # Only comment when there are code changes
  require_changes: true
  # Show coverage for changed files
  hide_project_coverage: true
